- name: Create default Service Monitor manifest
  set_fact:
    servicemonitor_manifest: {{ lookup('template', './manifest_servicemonitors.j2') | from_yaml }}
  when: servicemonitor_manifest is not defined

- name: Create ServiceMonitor to scrape Smart Gateway
  k8s:
    state: '{{ "present" if servicetelemetry_vars.backends.metrics.prometheus.enabled else "absent" }}'
    definition:
      '{{ servicemonitor_manifest }}'
